os:
  - linux
  - windows
sudo: required
language: node_js
node_js:
  - '12'
  - '14'
install:
  - npm install --unsafe-perm
script:
  - 'npm run test:package'
  - 'npm run test:unit'
  - 'npm run test:integration'
  - 'if [ "$TRAVIS_OS_NAME" != "windows" ]; then if [ "$TRAVIS_COMMIT_RANGE" != "" ]; then COMMIT_RANGE=$TRAVIS_COMMIT_RANGE; else COMMIT_RANGE="HEAD^..HEAD"; fi; echo "Lint check of commit range $COMMIT_RANGE"; lint-diff $COMMIT_RANGE; fi;'